spring:
  application:
    name: SubmissionService

  datasource:
    username: root
    password: 899961
    url: jdbc:mysql://localhost:3306/api
    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      maximum-pool-size: 40
#      minimum-idle: 10
#      auto-commit: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect


grpc:
  client:
    codeSubmission:
      address: "static://localhost:9091"
      negotiationType: PLAINTEXT

    TestCaseService:
      address: "static://localhost:9092"
      negotiationType: PLAINTEXT

    UserHistoryManagement:
      address: "static://localhost:9093"
      negotiationType: plaintext

server:
  port: 9099

logging:
  level:
    org:
      springframework:
        web: DEBUG
