version: "3.9"

x-logging:
  &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100M

services:

  # Load Balancer for Judge0 execution servers
  nginx-lb:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "2358:2358"  # Expose to frontend/backend
    depends_on:
      - worker1
      - worker2
    restart: always
    <<: *default-logging

  # Judge0 Execution Servers
  worker1:
    image: judge0/judge0:1.13.1
    command: ["./scripts/workers"]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    restart: always
    <<: *default-logging
    depends_on:
      - db
      - redis

  worker2:
    image: judge0/judge0:1.13.1
    command: ["./scripts/workers"]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    restart: always
    <<: *default-logging
    depends_on:
      - db
      - redis

  # Add more workers as needed
  # worker3:
  #   ...

  # Centralized PostgreSQL DB
  db:
    image: postgres:16.2
    env_file: judge0.conf
    volumes:
      - data:/var/lib/postgresql/data/
    restart: always
    <<: *default-logging

  # Redis Queue (Optional)
  redis:
    image: redis:7.2.4
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly no --requirepass "$$REDIS_PASSWORD"'
    ]
    env_file: judge0.conf
    restart: always
    <<: *default-logging

volumes:
  data:


# Use this commands
# docker-compose up -d db redis
# docker-compose up -d